seed: 5
freqSave: 1000
freqTest: 5000
nbTest: 1
freqVerbose: 100000
freqOptim: 200                                                                      # Optimisation de la politique tous les freqOptim evenements
fromFile: null
nbEpisodes: 1000
maxLengthTest: 500                                                                    # Longueur maxi des trajectoires en Test
maxLengthTrain: 200                                                              # Longueur maxi des trajectoires en Train

K_epochs: 50
rho: 0.995
discount: 0.99
batch_size: 100
sigma: 0.2
mu: 0
theta: 0.15
lr_a: 0.001
lr_c: 0.001

nbAgent: 1



