env: Pendulum-v0
seed: 5
featExtractor: !!python/name:__main__.NothingToDo ''
freqSave: 1000
freqTest: 50000000000  # do not test duw to batch normalisation
nbTest: 1
freqVerbose: 200
freqOptim: 1000                                                                    # Optimisation de la politique tous les freqOptim evenements
fromFile: null
nbEpisodes: 5000000
maxLengthTest: 500                                                                    # Longueur maxi des trajectoires en Test
maxLengthTrain: 200                                                              # Longueur maxi des trajectoires en Train

# Train
K_epochs: 10  # number of time to learning (backpropagation time)
rho: 0.9  # soft update
discount: 0.99
lr_a: 0.001
lr_c: 0.01
lr_alpha: 0.0003  # temperature
alpha: 1.
target_entropy: 0.2  #
adaptive: True

# Memory
buffer_size: 1000000
batch_size: 300
