env: CartPole-v1                                                  # environnement
seed: 5
featExtractor: !!python/name:__main__.NothingToDo ''
freqSave: 1000
freqTest: 1000
nbTest: 1
freqVerbose: 1000

fromFile: null
nbEpisodes: 1000000
maxLengthTrain: 300
maxLengthTest: 500

mem_size: 10000
mini_batch_size: 100

# epsilon greedy
eps: 0.15
decay: 0.99999

# target network update step
C: 100

# gamma for temporal differential
discount: 0.9

# network learning rate
lr: 1e-3

# Optimisation de la politique tous les freqOptim evenements
freqOptim: 20
