env: Pendulum-v0 #LunarLanderContinuous-v2                                               # environnement
seed: 5
featExtractor: !!python/name:__main__.NothingToDo ''
freqSave: 1000
freqTest: 5000
nbTest: 1
freqVerbose: 100000
freqOptim: 200                                                                    # Optimisation de la politique tous les freqOptim evenements
fromFile: null
nbEpisodes: 5000
maxLengthTest: 500                                                                    # Longueur maxi des trajectoires en Test
maxLengthTrain: 200                                                              # Longueur maxi des trajectoires en Train


K_epochs: 20  # number of time to learning (backpropagation time)
rho: 0.995  # soft update
discount: 0.99
batch_size: 128
lr_a: 0.0001
lr_c: 0.0001
lr_alpha: 0.0003  # temperature
alpha: 1.
target_entropy: 0.2  #
adaptive: True



