name: exo3_rnn_hangzhou_20.yaml
# Nombre de stations utilisé
CLASSES: 10
#Longueur des séquences
LENGTH: 20
# Dimension de l'entrée (1 (in) ou 2 (in/out))
DIM_INPUT: 2
DIM_LATENT: 100
#Taille du batch
BATCH_SIZE: 32

epoch: 1000
device: 'cuda'